baseURL = "https://maalshekto.github.io/carnet-migration-interieure/"
title = "Carnet de Migration Intérieure"
theme = "PaperMod"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true

# Mettre en production plus tard :
# baseURL = "https://ton-nom-de-domaine" (quand tu le décideras)

[params]
  disableThemeToggle = true
  themeColor = "#596e79"
  contentWidth = "900px"
  homeInfoParams = false
  disableSpecial1stPost = true
  author = "Thomas" # ou le pseudo de ton choix
  description = "Explorations progressives sur le réel, la migration intérieure et la densification de la présence."
  defaultTheme = "auto" # (clair/sombre en fonction du navigateur)
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  comments = false
  toc = true

[menu]
  [[menu.main]]
    name = "Explorations"
    url = "/explorations/"
    weight = 1

  [[menu.main]]
    name = "Instantanés"
    url = "/instantanes/"
    weight = 2

  [[menu.main]]
    name = "Meta"
    url = "/meta/"
    weight = 3